version: "3.8"
services:

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: simulation_dev
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount the init.sql file
    ports:
      - "3307:3306"

  api_real_estate:
    build: .
    volumes:
      - .:/app
    ports:
      - "5050:5000"
    container_name: api_service

volumes:
  mysql_data: